USE [AdministracionPeliculas]
GO
/****** Object:  Table [dbo].[ACTOR]    Script Date: 28-Jun-22 3:06:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACTOR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_COMPLETO] [varchar](50) NOT NULL,
	[SEXO] [char](1) NOT NULL,
	[FECHA_NACIMIENTO] [date] NOT NULL,
	[FOTO_ACTOR] [image] NULL,
 CONSTRAINT [PK_ACTOR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PELICULAS]    Script Date: 28-Jun-22 3:06:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PELICULAS](
	[ID_PELICULA] [int] IDENTITY(1,1) NOT NULL,
	[TITULO_PELICULA] [varchar](50) NOT NULL,
	[GENERO] [varchar](40) NOT NULL,
	[FECHA_ESTRENO] [date] NOT NULL,
	[FOTO_PELICULA] [image] NULL,
 CONSTRAINT [PK_PELICULAS] PRIMARY KEY CLUSTERED 
(
	[ID_PELICULA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[ACTOR] ON 

INSERT [dbo].[ACTOR] ([ID], [NOMBRE_COMPLETO], [SEXO], [FECHA_NACIMIENTO], [FOTO_ACTOR]) VALUES (1, N'Raymod Pozo', N'M', CAST(N'1969-08-08' AS Date), 0x)
INSERT [dbo].[ACTOR] ([ID], [NOMBRE_COMPLETO], [SEXO], [FECHA_NACIMIENTO], [FOTO_ACTOR]) VALUES (4, N'Jakie Chan', N'M', CAST(N'1954-07-04' AS Date), 0x)
INSERT [dbo].[ACTOR] ([ID], [NOMBRE_COMPLETO], [SEXO], [FECHA_NACIMIENTO], [FOTO_ACTOR]) VALUES (6, N'Jakie Chan', N'M', CAST(N'1954-04-07' AS Date), 0x)
INSERT [dbo].[ACTOR] ([ID], [NOMBRE_COMPLETO], [SEXO], [FECHA_NACIMIENTO], [FOTO_ACTOR]) VALUES (7, N'Mary Elizabeth Winstead', N'F', CAST(N'1984-11-28' AS Date), 0x)
INSERT [dbo].[ACTOR] ([ID], [NOMBRE_COMPLETO], [SEXO], [FECHA_NACIMIENTO], [FOTO_ACTOR]) VALUES (8, N'Fausto Mata', N'M', CAST(N'1971-10-13' AS Date), 0x)
INSERT [dbo].[ACTOR] ([ID], [NOMBRE_COMPLETO], [SEXO], [FECHA_NACIMIENTO], [FOTO_ACTOR]) VALUES (9, N'Nashla Bogaret', N'F', CAST(N'1986-05-11' AS Date), 0x)
SET IDENTITY_INSERT [dbo].[ACTOR] OFF
GO
SET IDENTITY_INSERT [dbo].[PELICULAS] ON 

INSERT [dbo].[PELICULAS] ([ID_PELICULA], [TITULO_PELICULA], [GENERO], [FECHA_ESTRENO], [FOTO_PELICULA]) VALUES (3, N'Tuberculo Gourmet', N'Comedia', CAST(N'2015-11-26' AS Date), 0x)
INSERT [dbo].[PELICULAS] ([ID_PELICULA], [TITULO_PELICULA], [GENERO], [FECHA_ESTRENO], [FOTO_PELICULA]) VALUES (4, N'Una pareja explosiva', N'Accion', CAST(N'1998-09-18' AS Date), 0x)
INSERT [dbo].[PELICULAS] ([ID_PELICULA], [TITULO_PELICULA], [GENERO], [FECHA_ESTRENO], [FOTO_PELICULA]) VALUES (5, N'Duro de Matar', N'Accion', CAST(N'1988-07-22' AS Date), 0x)
INSERT [dbo].[PELICULAS] ([ID_PELICULA], [TITULO_PELICULA], [GENERO], [FECHA_ESTRENO], [FOTO_PELICULA]) VALUES (6, N'Feo de dia, lindo de noche', N'Comedia', CAST(N'2012-09-13' AS Date), 0x)
INSERT [dbo].[PELICULAS] ([ID_PELICULA], [TITULO_PELICULA], [GENERO], [FECHA_ESTRENO], [FOTO_PELICULA]) VALUES (7, N'Lo que siento por ti', N'Drama', CAST(N'2018-10-29' AS Date), 0x)
SET IDENTITY_INSERT [dbo].[PELICULAS] OFF
GO
